[project]
name = "lekturio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KrzysDev", email = "krzysiekk.sokolowski@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "easyocr>=1.7.2",
    "fastapi>=0.141.1",
    "ollama>=0.6.2",
    "pdf2image>=1.17.0",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.4",
    "pymupdf>=1.28.2",
    "pypdf>=6.16.2",
    "pypdfium2>=5.13.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
lekturio = "lekturio:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
